apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    app: elastic-cluster
    role: master    
spec:
  clusterIP: None
  selector:
    app: elastic-cluster
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP