apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    app: elastic-cluster
    role: data
spec:
  type: ClusterIP
  selector:
    app: elastic-cluster
    role: data
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
    protocol: TCP