apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  labels:
    app: elastic-cluster
    role: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elastic-cluster
  template:
    metadata:
      labels:
        app: elastic-cluster
        role: master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: elastic-cluster
                  role: master
              topologyKey: kubernetes.io/hostname
      volumes:
      - name: elastic-configmap
        configMap:
          defaultMode: 0777
          name: elastic-configmap
          items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
            - key: jvm.options
              path: jvm.options
            - key: log4j2.properties
              path: log4j2.properties
      - name: storage
        emptyDir:
          medium: ""  
      - name: logs
        emptyDir:
          medium: ""
      initContainers:
        # just basic ES environment configuration
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
      - name: master
        image: lokacjusz/centos-elastic:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          privileged: true
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
          - name: NODE_MASTER
            value: "true"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_DATA
            value: "false"
          - name: NODE_INGEST
            value: "false"
          - name: NETWORK_HOST
            value: "0.0.0.0"
          - name: REPO_LOCATIONS
            value: "/data/repo"
          - name: MEMORY_LOCK
            value: "false"
          - name: HTTP_CORS_ENABLE
            value: "true"
          - name: HTTP_CORS_ALLOW_ORIGIN
            value: "true"
          - name: DISCOVERY_SERVICE
            value: "elasticsearch-discovery"
          - name: NUMBER_OF_MASTERS
            value: "2"
          - name: MAX_LOCAL_STORAGE_NODES
            value: "20"
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            name: elastic-configmap
            subPath: elasticsearch.yml
          - mountPath: /usr/share/elasticsearch/config/jvm.options
            name: elastic-configmap
            subPath: jvm.options
          - mountPath: /usr/share/elasticsearch/config/log4j2.properties
            name: elastic-configmap
            subPath: log4j2.properties
          - name: storage
            mountPath: /data
          - name: logs
            mountPath: /data/log