apiVersion: v1
kind: PersistentVolume
metadata:
  name: ela-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /elaData
    server: 192.168.56.2